apiVersion: v1
kind: Service
metadata:
  name: loan-approval-service
spec:
  selector:
    app: loan-approval
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  # ClusterIP is used for local Kind access via kubectl port-forward
  type: ClusterIP
